'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class mlsCatalan
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GameLauncher.mlsCatalan", GetType(mlsCatalan).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher
        '''© 2012-2013 xdpirate
        '''Provat inicialment per Kurithas.
        '''Un agraïment especial a la Llisa pel seu suport..
        '''</summary>
        Friend Shared ReadOnly Property AboutFormAuthorNote() As String
            Get
                Return ResourceManager.GetString("AboutFormAuthorNote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Tancar.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormCloseButtonText() As String
            Get
                Return ResourceManager.GetString("AboutFormCloseButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contactar.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormContactText() As String
            Get
                Return ResourceManager.GetString("AboutFormContactText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hi ha una nova versió de Game Launcher disponible (v.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormNewVersion1() As String
            Get
                Return ResourceManager.GetString("AboutFormNewVersion1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vols descarregar-la ara?.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormNewVersion2() As String
            Get
                Return ResourceManager.GetString("AboutFormNewVersion2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cercar actualitzacions.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpdateCheckButtonText() As String
            Get
                Return ResourceManager.GetString("AboutFormUpdateCheckButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to S&apos;ha produït un error tot cercant actualitzacions:.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpdateError1() As String
            Get
                Return ResourceManager.GetString("AboutFormUpdateError1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Si us plau intenta-ho de nou més tard o contacta amb l&apos;autor, si el problema persisteix..
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpdateError2() As String
            Get
                Return ResourceManager.GetString("AboutFormUpdateError2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La teva instal·lació de Game Launcher està actualitzada!.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpToDate() As String
            Get
                Return ResourceManager.GetString("AboutFormUpToDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lloc web.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormWebsiteLinkText() As String
            Get
                Return ResourceManager.GetString("AboutFormWebsiteLinkText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Buscar....
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormBrowseButtons() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormBrowseButtons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fes clic en aquest botó per seleccionar l&apos;executable utilitzat per iniciar el joc. Sol ser un arxiu amb extensió .exe.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormBrowseExeHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormBrowseExeHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cancel·lar.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCancelButton() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCancelButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fes clic en aquest botó per cancel·lar l&apos;addició d&apos;aquest joc. Si tens més jocs en cua per ser afegits (per exemple, si has fet servir el desplegable o el botó dret de l&apos;explorador), hauràs de cancel·lar-ho tot..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCancelHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCancelHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Introdueixi els paràmetres de la línia de comandes que s&apos;utilitzen per iniciar el joc. Si no saps el que és això, pots deixar-ho en blanc..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCmdArgsHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCmdArgsHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paràmetres de la línia de comandes:.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCmdArgsLabel() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCmdArgsLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fes clic en aquest botó per seleccionar una icona personalitzada. Ha de ser una imatge BMP, PNG, GIF, JPG o ICO, i serà redimensionada a 16x16. També pots especificar un arxiu EXE d&apos;on extreure la icona principal. La imatge mantindrà la seva relació d&apos;aspecte..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCustomIconHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCustomIconHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Passa el ratolí sobre un element per mostrar l&apos;ajuda en aquest panell..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormDefaultHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormDefaultHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Has d&apos;especificar una icona si &quot;Obtenir d&apos;un altre fitxer&quot; està seleccionat..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorGetFromOtherFileNoIcon() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorGetFromOtherFileNoIcon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No s&apos;ha trobat el fitxer executable de llançament: .
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorLauncherExeNotFound() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorLauncherExeNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No s&apos;ha trobat el fitxer executable del joc principal: .
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorMainExeNotFound() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorMainExeNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Has d&apos;introduir la ID de Steam App per aquest joc..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoAppId() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoAppId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ha d&apos;especificar una ruta  per l&apos;arxiu llançador..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoLauncherPath() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoLauncherPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Has d&apos;especificar una ruta per l&apos;arxiu executable principal..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoMainPath() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoMainPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Has d&apos;especificar un nom per al joc..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoName() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Has d&apos;especificar una ruta d&apos;accés a l&apos;executable que Steam fa servir per iniciar el joc..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoSteamExePath() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoSteamExePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No pots seleccionar la opció &quot;Obtenir des de executable&quot; per la icona sense especificar un arxiu executable per a un joc de Steam..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoSteamExePathClickedGetFromExecutable() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoSteamExePathClickedGetFromExecutable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Has d&apos;especificar una icona per a aquest joc de Steam..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoSteamIcon() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoSteamIcon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No s&apos;ha pogut trobar l&apos;executable per al joc de Steam:.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorSteamExeNotFound() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorSteamExeNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Informació del joc.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGameInfoGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGameInfoGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Introdueix aquí el nom del joc que vols afegir. Pots escriure qualsevol nom, però els signes d&apos;igual (=) es canviaran per guions (-) degut a limitacions tècniques..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGameNameHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGameNameHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nom:.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGameNameLabel() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGameNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ruta del joc/ID de Steam app.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGamePathsGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGamePathsGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selecciona aquesta opció si vols que Game Launcher obtingui la icona del joc de l&apos;executable del joc escollit..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromExeHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromExeHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Obtenir de l&apos;executable.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromExeRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromExeRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selecciona aquesta opció si vols especificar una icona tu mateix..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromOtherFileHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromOtherFileHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Obtenir d&apos;un altre fitxer.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromOtherFileRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromOtherFileRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ajuda.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormHelpGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormHelpGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Icona.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormIconGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormIconGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aquí pots veure una vista prèvia de la icona que es farà servir. Si has indicat que Game Launcher ha de recuperar la icona del executable del joc, hauràs d&apos;especificar l&apos;executable per tal d&apos;actualitzar aquesta previsualització..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormIconHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormIconHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mantenir la icona actual.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormKeepIconRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormKeepIconRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prem aquest botó per seleccionar el llançador utilitzat per llançar l&apos;executable principal del joc..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormLauncherBrowseHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormLauncherBrowseHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selecciona aquesta opció si es tracta d&apos;un joc normal (és a dir, que no és de Steam)..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormNormalGameHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormNormalGameHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Joc normal.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormNormalGameRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormNormalGameRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;D&apos;acord.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormOKButton() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormOKButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fes clic en aquest botó quan hagis acabat d&apos;omplir els detalls del joc que vols afegir..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormOKHelp() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormOKHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indica l&apos;executable.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSpecifySteamExeCheckBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSpecifySteamExeCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Marca aquesta casella per seleccionar l&apos;executable que Steam utilitzarà per executar el joc. Activant-la permetràs el seguiment de temps de joc per als jocs de Steam. Si el joc fa servir un llançador, no cap que marquis la casella, només ha de seleccionar l&apos;executable principal del joc..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSpecifySteamExeHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSpecifySteamExeHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Introdueix aquí la ID de Steam App. Per trobar la ID, busca el joc a la botiga de Steam i copia la identificació de l&apos;última part de la URL (per exemple a http://store.steampowered.com/app/24980/ -&gt; la ID és 24980).
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamAppIdHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamAppIdHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fes clic aquí per buscar l&apos;executable principal que Steam utilitzarà per executar el joc..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamExeBrowseHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamExeBrowseHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Joc a Steam.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamGameRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamGameRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selecciona aquesta opció si aquest és un joc que ha de ser iniciat a través de Steam..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afegir o modificar un joc.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormTitleBar() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fa servir un llançador.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormUsesLauncherCheckBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormUsesLauncherCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Marca aquesta casella si el joc que vols afegir utilitza un llançador. Un llançador és un executable que iniciarà el joc principal. Activant-la permetrà el seguiment de temps de joc per als jocs que requereixen fer servir un llançador..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormUsesLauncherHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormUsesLauncherHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Always on top.
        '''</summary>
        Friend Shared ReadOnly Property DockFormMenuAlwaysOnTop() As String
            Get
                Return ResourceManager.GetString("DockFormMenuAlwaysOnTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change opacity.
        '''</summary>
        Friend Shared ReadOnly Property DockFormMenuChangeOpacity() As String
            Get
                Return ResourceManager.GetString("DockFormMenuChangeOpacity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close the dock.
        '''</summary>
        Friend Shared ReadOnly Property DockFormMenuClose() As String
            Get
                Return ResourceManager.GetString("DockFormMenuClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opacitat de la barra quan tingui en focus (el ratolí passa per sobre la barra).
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormHoverOpacityGroupBox() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormHoverOpacityGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opacitat de la barra quan no tingui en focus.
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormNormalOpacityGroupBox() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormNormalOpacityGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Desar.
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormSaveButton() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormSaveButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Canviar la opacitat.
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormTitleBar() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deixa anar un accés directe o executable aquí!.
        '''</summary>
        Friend Shared ReadOnly Property DragDropTargetFormTitleBar() As String
            Get
                Return ResourceManager.GetString("DragDropTargetFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enllaç copiat al porta-papers!.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormCopiedToClipBoardText() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormCopiedToClipBoardText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Copiar.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormCopyButton() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormCopyButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Urls curtes cortesia de is.gd.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormCourtesyLabel() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormCourtesyLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mot bé! Envia l&apos;enllaç de sota als teus amics i estimats:.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormFlavorTextLabel() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormFlavorTextLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Tancar.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormGTFOButton() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormGTFOButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gràfic enllaçable.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormTitleBar() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Visitar enllaç.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormVisitLinkButton() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormVisitLinkButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comprovar automàticament si hi ha actualitzacions.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormAutoUpdateCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormAutoUpdateCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afegir a &amp;Game Launcher.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormExplorerIntegrationText() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormExplorerIntegrationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Tancar.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormGTFOButton() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormGTFOButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Els canvis tenen efecte immediatament..
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormInfoLabel() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormInfoLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Integrar amb l&apos;Explorador de Windows.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormIntegrateWithExplorerCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormIntegrateWithExplorerCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mostrar el temps dedicat al sortir del joc.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormPlayTimeInSkypeNotificationsCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormPlayTimeInSkypeNotificationsCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preferències.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormPreferencesGroupBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormPreferencesGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enviar notificacions per Skype quan comencis o acabis de jugar.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormSkypeNotificationsCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormSkypeNotificationsCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Iniciar Game Launcher quan iniciïs sessió.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormStartOnLoginCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormStartOnLoginCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preferències de Game Launcher.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormTitleBar() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alguna cosa ha fallat! . NET Framework diu:.
        '''</summary>
        Friend Shared ReadOnly Property MainFormAddGameFailed1() As String
            Get
                Return ResourceManager.GetString("MainFormAddGameFailed1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Si creus que això és un error, o el missatge d&apos;error persisteix, posa&apos;t en contacte amb l&apos;autor..
        '''</summary>
        Friend Shared ReadOnly Property MainFormAddGameFailed2() As String
            Get
                Return ResourceManager.GetString("MainFormAddGameFailed2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prem botó dret en aquesta icona o prem Windows+G per obrir la llista.
        '''</summary>
        Friend Shared ReadOnly Property MainFormBalloonTipLoadedMessageText() As String
            Get
                Return ResourceManager.GetString("MainFormBalloonTipLoadedMessageText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher v{0} carregat!.
        '''</summary>
        Friend Shared ReadOnly Property MainFormBalloonTipLoadedMessageTitle() As String
            Get
                Return ResourceManager.GetString("MainFormBalloonTipLoadedMessageTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Explore Game Folder.
        '''</summary>
        Friend Shared ReadOnly Property MainFormBrowseItemFolder() As String
            Get
                Return ResourceManager.GetString("MainFormBrowseItemFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There doesn&apos;t seem to be a path defined for this game..
        '''</summary>
        Friend Shared ReadOnly Property MainFormBrowseItemFolderNoPath() As String
            Get
                Return ResourceManager.GetString("MainFormBrowseItemFolderNoPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opens this game&apos;s folder in Windows Explorer.
        '''</summary>
        Friend Shared ReadOnly Property MainFormBrowseItemFolderTooltip() As String
            Get
                Return ResourceManager.GetString("MainFormBrowseItemFolderTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estàs segur de voler suprimir tots els elements de la llista? Aquesta acció NO es pot desfer!.
        '''</summary>
        Friend Shared ReadOnly Property MainFormClearGameList() As String
            Get
                Return ResourceManager.GetString("MainFormClearGameList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editar &amp;joc....
        '''</summary>
        Friend Shared ReadOnly Property MainFormEditGameItem() As String
            Get
                Return ResourceManager.GetString("MainFormEditGameItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editar les propietats d&apos;aquest joc.
        '''</summary>
        Friend Shared ReadOnly Property MainFormEditGameItemTooltip() As String
            Get
                Return ResourceManager.GetString("MainFormEditGameItemTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher està carregant, si us plau espera....
        '''</summary>
        Friend Shared ReadOnly Property MainFormLoadingMessage() As String
            Get
                Return ResourceManager.GetString("MainFormLoadingMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hi ha una nova versió de Game Launcher disponible (v {0})! Vols descarregar-la ara?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormNewVersionAvailable1() As String
            Get
                Return ResourceManager.GetString("MainFormNewVersionAvailable1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Si decideixes no actualitzar ara, la comprovació de noves versions es desactivarà fins la propera sessió..
        '''</summary>
        Friend Shared ReadOnly Property MainFormNewVersionAvailable2() As String
            Get
                Return ResourceManager.GetString("MainFormNewVersionAvailable2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Opcions.
        '''</summary>
        Friend Shared ReadOnly Property MainFormOptionsItem() As String
            Get
                Return ResourceManager.GetString("MainFormOptionsItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Segur que vols sortir de Game Launcher?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormQuitApplication() As String
            Get
                Return ResourceManager.GetString("MainFormQuitApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Sortir.
        '''</summary>
        Friend Shared ReadOnly Property MainFormQuitItem() As String
            Get
                Return ResourceManager.GetString("MainFormQuitItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estas segur de voler suprimir tots els paràmetres de línia de comandes per {0}?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveCmdArgs() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveCmdArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Es&amp;borrar....
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveGameItem() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveGameItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esborrar aquest joc de la llista.
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveGameItemTooltip() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveGameItemTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Segur que vols esborrar {0} de la llista?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveGameMsg() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveGameMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selecciona la icona de &quot;{0}&quot;.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSelectIconText() As String
            Get
                Return ResourceManager.GetString("MainFormSelectIconText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Està jugant a: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypeNowPlaying() As String
            Get
                Return ResourceManager.GetString("MainFormSkypeNowPlaying", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Està jugant a: {0} (Steam).
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypeNowPlayingSteam() As String
            Get
                Return ResourceManager.GetString("MainFormSkypeNowPlayingSteam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A parat de jugar a: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypePlayStopped() As String
            Get
                Return ResourceManager.GetString("MainFormSkypePlayStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  (Ha jugat: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypePlayTimeStopped() As String
            Get
                Return ResourceManager.GetString("MainFormSkypePlayTimeStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to hores.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeHourPlural() As String
            Get
                Return ResourceManager.GetString("MainFormTimeHourPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to hora.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeHourSingular() As String
            Get
                Return ResourceManager.GetString("MainFormTimeHourSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minuts.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeMinutePlural() As String
            Get
                Return ResourceManager.GetString("MainFormTimeMinutePlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minut.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeMinuteSingular() As String
            Get
                Return ResourceManager.GetString("MainFormTimeMinuteSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to segons.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeSecondPlural() As String
            Get
                Return ResourceManager.GetString("MainFormTimeSecondPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to segon.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeSecondSingular() As String
            Get
                Return ResourceManager.GetString("MainFormTimeSecondSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mostrar informació sobre l&apos;aplicació i els seus col·laboradors..
        '''</summary>
        Friend Shared ReadOnly Property MainMenuAboutTooltip() As String
            Get
                Return ResourceManager.GetString("MainMenuAboutTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afegeix un joc a la llista. També pots fer doble clic a la barra de icones per afegir jocs ràpidament arrossegant i deixant anar els accessos directes o executables allà..
        '''</summary>
        Friend Shared ReadOnly Property MainMenuAddGameTooltip() As String
            Get
                Return ResourceManager.GetString("MainMenuAddGameTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esborra tots els articles de la llista de jocs. Aquesta acció no es pot desfer!.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuClearGameListTooltip() As String
            Get
                Return ResourceManager.GetString("MainMenuClearGameListTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Opcions.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptions() As String
            Get
                Return ResourceManager.GetString("MainMenuOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sobre &amp;Game Launcher.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsAbout() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsAbout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Afegir joc....
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsAddGame() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsAddGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Buidar llista de jocs....
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsClearGameList() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsClearGameList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Preferències.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsPreferences() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsPreferences", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Esborrar jocs....
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsRemoveGames() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsRemoveGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Estadístiques.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsStatistics() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsStatistics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Sortir.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuQuit() As String
            Get
                Return ResourceManager.GetString("MainMenuQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esborrar un o més jocs de la llista..
        '''</summary>
        Friend Shared ReadOnly Property MainMenuRemoveGamesTooltip() As String
            Get
                Return ResourceManager.GetString("MainMenuRemoveGamesTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esborrar dades....
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormClearDataLinkText() As String
            Get
                Return ResourceManager.GetString("PieChartFormClearDataLinkText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Tancar.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormCloseButtonText() As String
            Get
                Return ResourceManager.GetString("PieChartFormCloseButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Generar gràfic enllaçable.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormGenerateChartButton() As String
            Get
                Return ResourceManager.GetString("PieChartFormGenerateChartButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Etiquetes internes.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormLabelPickerInside() As String
            Get
                Return ResourceManager.GetString("PieChartFormLabelPickerInside", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sense etiquetes.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormLabelPickerNone() As String
            Get
                Return ResourceManager.GetString("PieChartFormLabelPickerNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Etiquetes externes.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormLabelPickerOutside() As String
            Get
                Return ResourceManager.GetString("PieChartFormLabelPickerOutside", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vaja! Sembla que no hi ha cap dada gravada. Juga a algun joc i torna després!.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormNoData() As String
            Get
                Return ResourceManager.GetString("PieChartFormNoData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Si us plau espera.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormPleaseWait() As String
            Get
                Return ResourceManager.GetString("PieChartFormPleaseWait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Desar com a imatge....
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSaveAsImageButton() As String
            Get
                Return ResourceManager.GetString("PieChartFormSaveAsImageButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El teu gràfic s&apos;ha desat!.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSaveAsImageSuccess() As String
            Get
                Return ResourceManager.GetString("PieChartFormSaveAsImageSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Desar gràfic com a imatge.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSaveAsImageTitleBar() As String
            Get
                Return ResourceManager.GetString("PieChartFormSaveAsImageTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mostra llegenda.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormShowLegendCheckBox() As String
            Get
                Return ResourceManager.GetString("PieChartFormShowLegendCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ordena alfabèticament.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSortingPickerAlphabetically() As String
            Get
                Return ResourceManager.GetString("PieChartFormSortingPickerAlphabetically", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ordenar per més jugat.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSortingPickerByMostPlayed() As String
            Get
                Return ResourceManager.GetString("PieChartFormSortingPickerByMostPlayed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to d.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeDayShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeDayShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to h.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeHourShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeHourShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to m.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeMinuteShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeMinuteShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to s.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeSecondShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeSecondShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estadístiques de tems de joc de Game Launcher.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTitleBar() As String
            Get
                Return ResourceManager.GetString("PieChartFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Temps total de joc.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTotalPlayingTime() As String
            Get
                Return ResourceManager.GetString("PieChartFormTotalPlayingTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cancel·lar.
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormCancelButton() As String
            Get
                Return ResourceManager.GetString("RemoveFormCancelButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esteu segur de voler esborrar  els elements seleccionats?.
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormConfirmRemoval() As String
            Get
                Return ResourceManager.GetString("RemoveFormConfirmRemoval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Si us plau, selecciona els elements que vols eliminar. Prem la tecla CTRL per seleccionar més d&apos;un element a la vegada..
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormFlavorTextLabel() As String
            Get
                Return ResourceManager.GetString("RemoveFormFlavorTextLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No hi ha elements seleccionats..
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormNoItemsSelected() As String
            Get
                Return ResourceManager.GetString("RemoveFormNoItemsSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Esborrar element(s).
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormRemoveItemsButton() As String
            Get
                Return ResourceManager.GetString("RemoveFormRemoveItemsButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esborrar element(s).
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormTitleBar() As String
            Get
                Return ResourceManager.GetString("RemoveFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Traduït al català per kerheol.
        '''</summary>
        Friend Shared ReadOnly Property TranslationAuthor() As String
            Get
                Return ResourceManager.GetString("TranslationAuthor", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
