'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class mlsFinnish
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GameLauncher.mlsFinnish", GetType(mlsFinnish).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher
        '''© 2012-2013 xdpirate
        '''Beta testing by Kurithas.
        '''Special thanks to Lisa for support..
        '''</summary>
        Friend Shared ReadOnly Property AboutFormAuthorNote() As String
            Get
                Return ResourceManager.GetString("AboutFormAuthorNote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Sulje.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormCloseButtonText() As String
            Get
                Return ResourceManager.GetString("AboutFormCloseButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ota yhteyttä.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormContactText() As String
            Get
                Return ResourceManager.GetString("AboutFormContactText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcherista on saatavilla uusi versio..
        '''</summary>
        Friend Shared ReadOnly Property AboutFormNewVersion1() As String
            Get
                Return ResourceManager.GetString("AboutFormNewVersion1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Haluaisitko ladata sen nyt?.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormNewVersion2() As String
            Get
                Return ResourceManager.GetString("AboutFormNewVersion2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tarkista &amp;päivitysten saatavuus..
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpdateCheckButtonText() As String
            Get
                Return ResourceManager.GetString("AboutFormUpdateCheckButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Päivityksia etsittäessä on tapahtunut virhe:.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpdateError1() As String
            Get
                Return ResourceManager.GetString("AboutFormUpdateError1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yritä myöhemmin uudelleen, tai ota yhteyttä kehittäjään jos ongelma ei korjaannu..
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpdateError2() As String
            Get
                Return ResourceManager.GetString("AboutFormUpdateError2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcherisi on ajan tasalla!.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpToDate() As String
            Get
                Return ResourceManager.GetString("AboutFormUpToDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nettisivut.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormWebsiteLinkText() As String
            Get
                Return ResourceManager.GetString("AboutFormWebsiteLinkText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Selaa....
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormBrowseButtons() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormBrowseButtons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Klikkaa tästä valitaksesi suoritettava tiedosto. Se on yleensä .exe-tiedosto..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormBrowseExeHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormBrowseExeHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Peruuta.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCancelButton() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCancelButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Klikkaa tästä lopettaaksesi pelin lisäämisen. Jos sinulla on lisää pelejä lisäysjonossa (esim. jos käytät pudotusvalikkoikkunaa tai hiiren oikean napin klikkausta Explorerissa), sinun täytyy peruuttaa ne kaikki..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCancelHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCancelHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Syötä komentorivimuuttujat käytettäväksi pelin käynnistyksen yhteydessä. Jos et tiedä mitä tämä tekee, jätä se tyhjäksi..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCmdArgsHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCmdArgsHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Komentorivimuuttujat:.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCmdArgsLabel() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCmdArgsLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Klikkaa tästä valitaksesi mukautetun kuvakkeen. Sen täytyy olla BMP, PNG, GIF, JPG tai ICO tiedostomuodossa, ja sen koko muutetaan 16x16:ksi. Voit myös valita .exe-tiedoston käyttääksesi sen kuvaketta. Kuvakkeen kuvasuhde säilytetään..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCustomIconHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCustomIconHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kohdista kursori kohteeseen näyttääksesi ohjeita tässä paneelissa..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormDefaultHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormDefaultHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sinun täytyy määrittää kuvake, jos &quot;Tuo muusta tiedostosta&quot; on valittuna..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorGetFromOtherFileNoIcon() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorGetFromOtherFileNoIcon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suoritettavaa tiedostoa ei löytynyt: .
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorLauncherExeNotFound() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorLauncherExeNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pelin pääsuoritustiedostoa ei löytynyt: .
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorMainExeNotFound() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorMainExeNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sinun täytyy syöttää Steam App ID tälle pelille..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoAppId() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoAppId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sinun täytyy määrittää käynnistystiedoston polku..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoLauncherPath() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoLauncherPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sinun täytyy määrittää suoritettavan tiedoston polku..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoMainPath() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoMainPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sinun täytyy nimetä peli..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoName() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sinun täytyy määrittää suoritettavan tiedoston polku, jota Steam käyttää pelin käynnistykseen..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoSteamExePath() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoSteamExePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Et voi valita &quot;Tuo ajettavasta tiedostosta&quot; kuvakkeelle jos et ole määrittänyt Steam pelin suoritustiedostoa..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoSteamExePathClickedGetFromExecutable() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoSteamExePathClickedGetFromExecutable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sinun täytyy määrittää kuvake Steam pelille..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoSteamIcon() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoSteamIcon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Määritettyä suoritustiedosta Steam pelille ei löytynyt: .
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorSteamExeNotFound() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorSteamExeNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tietoa pelistä.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGameInfoGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGameInfoGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Syötä lisättävän pelin nimi tähän. Sen nimi voi olla mikä tahansa, mutta yhtäsuuruusmerkit (=) korvataan viivoilla (-) teknisten rajoitusten vuoksi..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGameNameHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGameNameHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nimi:.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGameNameLabel() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGameNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pelin /Steam app ID.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGamePathsGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGamePathsGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valitse tämä, jos haluat Game Launcherin hakevan pelin kuvakkeen sen käynnistystiedostosta..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromExeHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromExeHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tuo käynnistystiedostosta.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromExeRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromExeRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valitse tämä, jos haluat itse määrittää kuvakkeen..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromOtherFileHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromOtherFileHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tuo muusta tiedostosta.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromOtherFileRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromOtherFileRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apua.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormHelpGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormHelpGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kuvake.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormIconGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormIconGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tämä näyttää esikatselukuvan käytettävästä kuvakkeesta. Jos Game Launcher on asetettu tuomaan kuvake pelin käynnistystiedostosta, tämä esikatselu ei päivity ennen kuin olet määrittänyt tiedoston..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormIconHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormIconHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Säilytä nykyinen kuvake.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormKeepIconRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormKeepIconRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valitse tämä valitaksesi käynnistystiedoston pelin ajettavalle tiedostolle..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormLauncherBrowseHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormLauncherBrowseHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valitse tämä jos kyseessä on tavallinen peli (eli se ei tarvitse Steamia)..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormNormalGameHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormNormalGameHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tavallinen peli.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormNormalGameRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormNormalGameRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;OK.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormOKButton() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormOKButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Klikkaa tästä kun olet täyttänyt pelin tiedot..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormOKHelp() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormOKHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Määritä ajettava tiedosto.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSpecifySteamExeCheckBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSpecifySteamExeCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rastita tämä ruutu jos haluat valita ajettavan tiedoston jota Steam käyttää käynnistääkseen pelin. Tämän valitseminen mahdollistaa peliaikatilastojen seuraamisen Steam peleille. Jos peli käyttää käynnistystiedostoa, sinun ei tarvitse valita sitä, Valitse vain pääasiallinen ajettava tiedosto..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSpecifySteamExeHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSpecifySteamExeHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Syötä Steam App ID tähän. Löytääksesi ID:n, etsi peli Steam Storesta ja kopioi ID URL:n viimeisestä osasta (esim. http://store.steampowered.com/app/24980/ -&gt; ID tässä on 24980).
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamAppIdHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamAppIdHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Klikaa tästä selataksesi pääasiallista ajettavaa tiedosta, jota Steam käyttää..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamExeBrowseHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamExeBrowseHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Steam peli.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamGameRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamGameRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valitse tämä jos peli täytyy käynnistää Steamista..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lisää tai muokkaa peliä.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormTitleBar() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Käyttää käynnistystiedostoa.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormUsesLauncherCheckBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormUsesLauncherCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rastita tämä ruutu jos tämä peli käyttää käynnistystiedostoa. Käynnistystiedosto on tiedosto joka käynnistää pelin. Tämän valitseminen mahdollistaa peliaikatilastojen seuraamisen peleille jotka pitää käynnistää käynnistystiedostolla..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormUsesLauncherHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormUsesLauncherHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aina päällä.
        '''</summary>
        Friend Shared ReadOnly Property DockFormMenuAlwaysOnTop() As String
            Get
                Return ResourceManager.GetString("DockFormMenuAlwaysOnTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Muokkaa peittävyyttä.
        '''</summary>
        Friend Shared ReadOnly Property DockFormMenuChangeOpacity() As String
            Get
                Return ResourceManager.GetString("DockFormMenuChangeOpacity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sulje telakka.
        '''</summary>
        Friend Shared ReadOnly Property DockFormMenuClose() As String
            Get
                Return ResourceManager.GetString("DockFormMenuClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telakan peittävyys kohdistettuna (kun kursori on sen kohdalla).
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormHoverOpacityGroupBox() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormHoverOpacityGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telakan peittävyys kun se ei ole kohdistettuna.
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormNormalOpacityGroupBox() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormNormalOpacityGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Tallenna.
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormSaveButton() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormSaveButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Muokkaa peittävyyttä.
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormTitleBar() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pudota pikakuvake tai ajettava tiedosto tähän!.
        '''</summary>
        Friend Shared ReadOnly Property DragDropTargetFormTitleBar() As String
            Get
                Return ResourceManager.GetString("DragDropTargetFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Linkki kopioitiin leikepöydälle!.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormCopiedToClipBoardText() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormCopiedToClipBoardText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Kopioi.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormCopyButton() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormCopyButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lyhytlinkeistä kiitos is.gd :lle.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormCourtesyLabel() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormCourtesyLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Onnistui! Lähetä alla oleva linkki ystävillesi ja rakkaillesi:.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormFlavorTextLabel() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormFlavorTextLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sulj&amp;e.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormGTFOButton() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormGTFOButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Linkattava kartta.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormTitleBar() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Vieraile linkin osoitteessa.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormVisitLinkButton() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormVisitLinkButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tarkista päivitykset automaattisesti.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormAutoUpdateCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormAutoUpdateCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lisää &amp;Game Launcheriin.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormExplorerIntegrationText() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormExplorerIntegrationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Sulje.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormGTFOButton() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormGTFOButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Muutokset tulevat voimaan välittömästi..
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormInfoLabel() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormInfoLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Integroi Windows Explorerin kanssa.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormIntegrateWithExplorerCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormIntegrateWithExplorerCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Näytä peliaika poistuessani pelistä.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormPlayTimeInSkypeNotificationsCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormPlayTimeInSkypeNotificationsCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valinnat.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormPreferencesGroupBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormPreferencesGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lähetä ilmoitus Skypeen kun aloitat/lopetat pelaamisen.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormSkypeNotificationsCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormSkypeNotificationsCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Käynnistä Game Launcher kirjautuessasi sisään.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormStartOnLoginCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormStartOnLoginCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcherin valinnat.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormTitleBar() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jotain meni pieleen! .NET Framework sanoi:.
        '''</summary>
        Friend Shared ReadOnly Property MainFormAddGameFailed1() As String
            Get
                Return ResourceManager.GetString("MainFormAddGameFailed1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jos uskot tämän olevan bugi tai virheilmoitus säilyy, ota yhteyttä kehittäjään..
        '''</summary>
        Friend Shared ReadOnly Property MainFormAddGameFailed2() As String
            Get
                Return ResourceManager.GetString("MainFormAddGameFailed2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Klikkaa tätä kuvaketta hiiren oikealla tai paina Windows+G avataksesi listan.
        '''</summary>
        Friend Shared ReadOnly Property MainFormBalloonTipLoadedMessageText() As String
            Get
                Return ResourceManager.GetString("MainFormBalloonTipLoadedMessageText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher v{0} ladattiin!.
        '''</summary>
        Friend Shared ReadOnly Property MainFormBalloonTipLoadedMessageTitle() As String
            Get
                Return ResourceManager.GetString("MainFormBalloonTipLoadedMessageTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oletko varma, että haluat poistaa listan kaikki kohteet? Tätä toimintoa EI voi peruuttaa!.
        '''</summary>
        Friend Shared ReadOnly Property MainFormClearGameList() As String
            Get
                Return ResourceManager.GetString("MainFormClearGameList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Muokkaa &amp;peliä....
        '''</summary>
        Friend Shared ReadOnly Property MainFormEditGameItem() As String
            Get
                Return ResourceManager.GetString("MainFormEditGameItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Muokkaa tämän pelin asetuksia.
        '''</summary>
        Friend Shared ReadOnly Property MainFormEditGameItemTooltip() As String
            Get
                Return ResourceManager.GetString("MainFormEditGameItemTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher latautuu, ole hyvä ja odota....
        '''</summary>
        Friend Shared ReadOnly Property MainFormLoadingMessage() As String
            Get
                Return ResourceManager.GetString("MainFormLoadingMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcherista on saatavilla uusi versio (v{0})! Haluaisitko ladata sen nyt?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormNewVersionAvailable1() As String
            Get
                Return ResourceManager.GetString("MainFormNewVersionAvailable1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jos et halua päivittää nyt, uusien päivitysten tarkistaminen kytketään pois tästä istunnosta..
        '''</summary>
        Friend Shared ReadOnly Property MainFormNewVersionAvailable2() As String
            Get
                Return ResourceManager.GetString("MainFormNewVersionAvailable2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Asetukset.
        '''</summary>
        Friend Shared ReadOnly Property MainFormOptionsItem() As String
            Get
                Return ResourceManager.GetString("MainFormOptionsItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Haluatko varmasti lopettaa Game Launcherin?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormQuitApplication() As String
            Get
                Return ResourceManager.GetString("MainFormQuitApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Lopeta.
        '''</summary>
        Friend Shared ReadOnly Property MainFormQuitItem() As String
            Get
                Return ResourceManager.GetString("MainFormQuitItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Haluatko varmasti poistaa kaikki komentorivimuuttujat {0}:lle?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveCmdArgs() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveCmdArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to P&amp;oista....
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveGameItem() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveGameItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poista tämä peli listasta.
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveGameItemTooltip() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveGameItemTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Haluatko varmasti poistaa pelin {0} listasta?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveGameMsg() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveGameMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valitse kuvake pelille &quot;{0}&quot;.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSelectIconText() As String
            Get
                Return ResourceManager.GetString("MainFormSelectIconText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pelissä: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypeNowPlaying() As String
            Get
                Return ResourceManager.GetString("MainFormSkypeNowPlaying", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pelissä: {0} (Steam).
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypeNowPlayingSteam() As String
            Get
                Return ResourceManager.GetString("MainFormSkypeNowPlayingSteam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lopetti pelaamisen: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypePlayStopped() As String
            Get
                Return ResourceManager.GetString("MainFormSkypePlayStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Pelasi: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypePlayTimeStopped() As String
            Get
                Return ResourceManager.GetString("MainFormSkypePlayTimeStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tuntia.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeHourPlural() As String
            Get
                Return ResourceManager.GetString("MainFormTimeHourPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tunti.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeHourSingular() As String
            Get
                Return ResourceManager.GetString("MainFormTimeHourSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minuuttia.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeMinutePlural() As String
            Get
                Return ResourceManager.GetString("MainFormTimeMinutePlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minuutti.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeMinuteSingular() As String
            Get
                Return ResourceManager.GetString("MainFormTimeMinuteSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sekuntia.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeSecondPlural() As String
            Get
                Return ResourceManager.GetString("MainFormTimeSecondPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sekunti.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeSecondSingular() As String
            Get
                Return ResourceManager.GetString("MainFormTimeSecondSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Näytä tietoa ohjelman kehittäjästä ja avustajista..
        '''</summary>
        Friend Shared ReadOnly Property MainMenuAboutTooltip() As String
            Get
                Return ResourceManager.GetString("MainMenuAboutTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lisää peli listaan. Voit myös tuplaklikata telakkakuvaketta lisätäksesi pelejä nopeasti raahaamalla ja pudottamalla pikakuvakkeita tai ajettavia tiedostoja..
        '''</summary>
        Friend Shared ReadOnly Property MainMenuAddGameTooltip() As String
            Get
                Return ResourceManager.GetString("MainMenuAddGameTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poista kaikki kohteet listasta. Tätä toimintoa ei voi peruuttaa!.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuClearGameListTooltip() As String
            Get
                Return ResourceManager.GetString("MainMenuClearGameListTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Asetukset.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptions() As String
            Get
                Return ResourceManager.GetString("MainMenuOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tietoja &amp;Game Launcherista.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsAbout() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsAbout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Lisää peli....
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsAddGame() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsAddGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Tyhjennä lista....
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsClearGameList() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsClearGameList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Valinnat.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsPreferences() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsPreferences", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Poista pelit....
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsRemoveGames() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsRemoveGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Til&amp;astoja.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsStatistics() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsStatistics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&amp;opeta.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuQuit() As String
            Get
                Return ResourceManager.GetString("MainMenuQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poista yksi tai useampia pelejä listasta..
        '''</summary>
        Friend Shared ReadOnly Property MainMenuRemoveGamesTooltip() As String
            Get
                Return ResourceManager.GetString("MainMenuRemoveGamesTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tyhjennä....
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormClearDataLinkText() As String
            Get
                Return ResourceManager.GetString("PieChartFormClearDataLinkText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Sulje.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormCloseButtonText() As String
            Get
                Return ResourceManager.GetString("PieChartFormCloseButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Luo linkattava kartta.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormGenerateChartButton() As String
            Get
                Return ResourceManager.GetString("PieChartFormGenerateChartButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nimikkeitä sisäpuolella.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormLabelPickerInside() As String
            Get
                Return ResourceManager.GetString("PieChartFormLabelPickerInside", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ei nimikkeitä.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormLabelPickerNone() As String
            Get
                Return ResourceManager.GetString("PieChartFormLabelPickerNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nimikkeitä ulkopuolella.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormLabelPickerOutside() As String
            Get
                Return ResourceManager.GetString("PieChartFormLabelPickerOutside", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hups! Yhtään dataa ei ole vielä kerätty. Pelaa jotain ja tule sitten takaisin!.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormNoData() As String
            Get
                Return ResourceManager.GetString("PieChartFormNoData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ole hyvä ja odota.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormPleaseWait() As String
            Get
                Return ResourceManager.GetString("PieChartFormPleaseWait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Tallenna kuvana....
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSaveAsImageButton() As String
            Get
                Return ResourceManager.GetString("PieChartFormSaveAsImageButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kuvasi tallennettiin!.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSaveAsImageSuccess() As String
            Get
                Return ResourceManager.GetString("PieChartFormSaveAsImageSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tallenna ympyrädiagrammi kuvana.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSaveAsImageTitleBar() As String
            Get
                Return ResourceManager.GetString("PieChartFormSaveAsImageTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Näytä merkkien selitykset.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormShowLegendCheckBox() As String
            Get
                Return ResourceManager.GetString("PieChartFormShowLegendCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Järjestä aakkosiin.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSortingPickerAlphabetically() As String
            Get
                Return ResourceManager.GetString("PieChartFormSortingPickerAlphabetically", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Järjestä peliajan mukaan.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSortingPickerByMostPlayed() As String
            Get
                Return ResourceManager.GetString("PieChartFormSortingPickerByMostPlayed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to p.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeDayShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeDayShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to t.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeHourShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeHourShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to m.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeMinuteShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeMinuteShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to s.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeSecondShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeSecondShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher Peliajan Tilastot.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTitleBar() As String
            Get
                Return ResourceManager.GetString("PieChartFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kokonaispeliaika.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTotalPlayingTime() As String
            Get
                Return ResourceManager.GetString("PieChartFormTotalPlayingTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Peruuta.
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormCancelButton() As String
            Get
                Return ResourceManager.GetString("RemoveFormCancelButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oletko varma haluavasi poistaa valitut kohteet?.
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormConfirmRemoval() As String
            Get
                Return ResourceManager.GetString("RemoveFormConfirmRemoval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valitse poistettavat kohteet. Voit pitää pohjassa CTRL:ia valitaksesi useampia kohteita..
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormFlavorTextLabel() As String
            Get
                Return ResourceManager.GetString("RemoveFormFlavorTextLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ei valittuja kohteita..
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormNoItemsSelected() As String
            Get
                Return ResourceManager.GetString("RemoveFormNoItemsSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Poista kohteet.
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormRemoveItemsButton() As String
            Get
                Return ResourceManager.GetString("RemoveFormRemoveItemsButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Poista kohteet.
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormTitleBar() As String
            Get
                Return ResourceManager.GetString("RemoveFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suomenkielisen käännöksen teki Hakkapeliitta.
        '''</summary>
        Friend Shared ReadOnly Property TranslationAuthor() As String
            Get
                Return ResourceManager.GetString("TranslationAuthor", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
