'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class mlsNorwegian
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GameLauncher.mlsNorwegian", GetType(mlsNorwegian).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher
        '''© 2012-2013 xdpirate
        '''Betatesting av Kurithas.
        '''Mange takk til Lisa for hennes støtte.
        '''Takk for at du bruker programmet mitt!.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormAuthorNote() As String
            Get
                Return ResourceManager.GetString("AboutFormAuthorNote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Lukk.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormCloseButtonText() As String
            Get
                Return ResourceManager.GetString("AboutFormCloseButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kontakt.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormContactText() As String
            Get
                Return ResourceManager.GetString("AboutFormContactText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to En ny versjon av Game Launcher er tilgjengelig (v.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormNewVersion1() As String
            Get
                Return ResourceManager.GetString("AboutFormNewVersion1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vil du laste ned denne versjonen nå?.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormNewVersion2() As String
            Get
                Return ResourceManager.GetString("AboutFormNewVersion2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sjekk etter &amp;oppdateringer.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpdateCheckButtonText() As String
            Get
                Return ResourceManager.GetString("AboutFormUpdateCheckButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Det oppstod en feil ved sjekk av programoppdateringer:.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpdateError1() As String
            Get
                Return ResourceManager.GetString("AboutFormUpdateError1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vennligst prøv igjen senere, eller ta kontakt med forfatteren av dette programmet om problemet ikke løser seg..
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpdateError2() As String
            Get
                Return ResourceManager.GetString("AboutFormUpdateError2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Du har allerede nyeste versjon av Game Launcher!.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpToDate() As String
            Get
                Return ResourceManager.GetString("AboutFormUpToDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hjemmeside.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormWebsiteLinkText() As String
            Get
                Return ResourceManager.GetString("AboutFormWebsiteLinkText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Browse....
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormBrowseButtons() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormBrowseButtons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click this button to select the executable used to run the game. This is typically an .exe-file..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormBrowseExeHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormBrowseExeHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cancel.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCancelButton() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCancelButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click this button if you wish to cancel adding this game. If you have more games queued up to be added (e.g. if using the drop window or right-clicking items in Explorer), you will need to cancel them all..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCancelHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCancelHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter the command-line arguments to be used when launching the game. If you don&apos;t know what this is, you can leave it empty..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCmdArgsHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCmdArgsHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Command line arguments:.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCmdArgsLabel() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCmdArgsLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click this button to select a custom icon. It must be a BMP, PNG, GIF, JPG or ICO image, and will be resized to 16x16. You can also specify an EXE-file to extract its main icon and use it. The image will have its aspect ratio preserved..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCustomIconHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCustomIconHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hover over an item to show help in this panel..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormDefaultHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormDefaultHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must specify an icon if &quot;Get from other file&quot; is selected..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorGetFromOtherFileNoIcon() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorGetFromOtherFileNoIcon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The launcher executable could not be found: .
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorLauncherExeNotFound() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorLauncherExeNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The main game executable could not be found: .
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorMainExeNotFound() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorMainExeNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must enter the Steam App ID for the game..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoAppId() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoAppId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must specify a path to the launcher..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoLauncherPath() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoLauncherPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must specify a path for the main executable..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoMainPath() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoMainPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must specify a name for the game..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoName() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must specify a path to the executable Steam uses to launch the game..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoSteamExePath() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoSteamExePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You cannot select &quot;Get from executable&quot; for the icon if you haven&apos;t specified an executable for a Steam game..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoSteamExePathClickedGetFromExecutable() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoSteamExePathClickedGetFromExecutable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must specify an icon for this Steam game..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoSteamIcon() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoSteamIcon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The specified executable for the Steam game could not be found: .
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorSteamExeNotFound() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorSteamExeNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game information.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGameInfoGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGameInfoGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter the name of the game to be added here. It can be named anything, but equals signs (=) will be replaced with dashes (-) due to technical limitations..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGameNameHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGameNameHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name:.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGameNameLabel() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGameNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game path/Steam app ID.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGamePathsGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGamePathsGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select this option if you want Game Launcher to get the game icon from the chosen game executable..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromExeHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromExeHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Get from executable.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromExeRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromExeRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select this option if you want to specify an icon yourself..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromOtherFileHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromOtherFileHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Get from other file.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromOtherFileRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromOtherFileRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormHelpGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormHelpGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Icon.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormIconGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormIconGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This shows a preview of the icon that will be used. If Game Launcher is set to retrieve the icon from the executable for the game, you must specify the executable before this preview will update..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormIconHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormIconHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keep current icon.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormKeepIconRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormKeepIconRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click this button to select the launcher used to launch the main game executable..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormLauncherBrowseHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormLauncherBrowseHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select this option if this is a normal game (i.e. it does not use Steam)..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormNormalGameHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormNormalGameHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Normal game.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormNormalGameRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormNormalGameRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;OK.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormOKButton() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormOKButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Specify executable.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSpecifySteamExeCheckBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSpecifySteamExeCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check this box if you want to select the executable Steam uses to run the game. Enabling this will enable playtime tracking for Steam games. If the game uses a launcher, you do not need to select it, simply select the main executable the game runs from..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSpecifySteamExeHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSpecifySteamExeHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter the Steam App ID here. To find the ID, locate the game in the Steam Store, and copy the ID from the last part of the URL (e.g. http://store.steampowered.com/app/24980/ -&gt; The ID here is 24980).
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamAppIdHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamAppIdHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click here to browse for the main executable Steam uses to run the game..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamExeBrowseHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamExeBrowseHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Steam game.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamGameRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamGameRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select this option if this is a game that must be launched through Steam..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add or edit game.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormTitleBar() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uses a launcher.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormUsesLauncherCheckBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormUsesLauncherCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check this box if the game you are adding uses a launcher. A launcher is an executable that will in turn launch the main game. Enabling this will enable playtime tracking for games that require being launched with a launcher..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormUsesLauncherHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormUsesLauncherHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dock opacity when in focus (mouse hovering over the dock).
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormHoverOpacityGroupBox() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormHoverOpacityGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dock opacity when not in focus.
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormNormalOpacityGroupBox() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormNormalOpacityGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Save.
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormSaveButton() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormSaveButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change opacity.
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormTitleBar() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drop a shortcut or executable here!.
        '''</summary>
        Friend Shared ReadOnly Property DragDropTargetFormTitleBar() As String
            Get
                Return ResourceManager.GetString("DragDropTargetFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Link copied to the clipboard!.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormCopiedToClipBoardText() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormCopiedToClipBoardText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Copy.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormCopyButton() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormCopyButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shortlinks courtesy of is.gd.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormCourtesyLabel() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormCourtesyLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Success! Send the link below to your friends and loved ones:.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormFlavorTextLabel() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormFlavorTextLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clos&amp;e.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormGTFOButton() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormGTFOButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Linkable chart.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormTitleBar() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Visit link.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormVisitLinkButton() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormVisitLinkButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Automatically check for updates.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormAutoUpdateCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormAutoUpdateCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add to &amp;Game Launcher.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormExplorerIntegrationText() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormExplorerIntegrationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Close.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormGTFOButton() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormGTFOButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changes take effect immediately..
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormInfoLabel() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormInfoLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Integrate with Windows Explorer.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormIntegrateWithExplorerCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormIntegrateWithExplorerCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show time spent playing when exiting game.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormPlayTimeInSkypeNotificationsCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormPlayTimeInSkypeNotificationsCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preferences.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormPreferencesGroupBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormPreferencesGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send notifications to Skype when you start/stop playing.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormSkypeNotificationsCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormSkypeNotificationsCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start Game Launcher when you log in.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormStartOnLoginCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormStartOnLoginCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher Preferences.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormTitleBar() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Something went wrong! .NET Framework said:.
        '''</summary>
        Friend Shared ReadOnly Property MainFormAddGameFailed1() As String
            Get
                Return ResourceManager.GetString("MainFormAddGameFailed1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you believe this is a bug, or the error message persists, please contact the author..
        '''</summary>
        Friend Shared ReadOnly Property MainFormAddGameFailed2() As String
            Get
                Return ResourceManager.GetString("MainFormAddGameFailed2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Right-click this icon or press Windows+G to open the list.
        '''</summary>
        Friend Shared ReadOnly Property MainFormBalloonTipLoadedMessageText() As String
            Get
                Return ResourceManager.GetString("MainFormBalloonTipLoadedMessageText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher v{0} loaded!.
        '''</summary>
        Friend Shared ReadOnly Property MainFormBalloonTipLoadedMessageTitle() As String
            Get
                Return ResourceManager.GetString("MainFormBalloonTipLoadedMessageTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to remove all items in the list? This action CANNOT be undone!.
        '''</summary>
        Friend Shared ReadOnly Property MainFormClearGameList() As String
            Get
                Return ResourceManager.GetString("MainFormClearGameList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit &amp;game....
        '''</summary>
        Friend Shared ReadOnly Property MainFormEditGameItem() As String
            Get
                Return ResourceManager.GetString("MainFormEditGameItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit the properties of this game.
        '''</summary>
        Friend Shared ReadOnly Property MainFormEditGameItemTooltip() As String
            Get
                Return ResourceManager.GetString("MainFormEditGameItemTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher is loading, please wait....
        '''</summary>
        Friend Shared ReadOnly Property MainFormLoadingMessage() As String
            Get
                Return ResourceManager.GetString("MainFormLoadingMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is a new version of Game Launcher available (v{0})! Would you like to download it now?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormNewVersionAvailable1() As String
            Get
                Return ResourceManager.GetString("MainFormNewVersionAvailable1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If you decide not to update at this point, checking for new updates will be disabled for this session..
        '''</summary>
        Friend Shared ReadOnly Property MainFormNewVersionAvailable2() As String
            Get
                Return ResourceManager.GetString("MainFormNewVersionAvailable2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Options.
        '''</summary>
        Friend Shared ReadOnly Property MainFormOptionsItem() As String
            Get
                Return ResourceManager.GetString("MainFormOptionsItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to quit Game Launcher?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormQuitApplication() As String
            Get
                Return ResourceManager.GetString("MainFormQuitApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Quit.
        '''</summary>
        Friend Shared ReadOnly Property MainFormQuitItem() As String
            Get
                Return ResourceManager.GetString("MainFormQuitItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to remove all command-line arguments for {0}?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveCmdArgs() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveCmdArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Re&amp;move....
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveGameItem() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveGameItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove this game from the list.
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveGameItemTooltip() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveGameItemTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to remove {0} from the list?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveGameMsg() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveGameMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select icon for &quot;{0}&quot;.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSelectIconText() As String
            Get
                Return ResourceManager.GetString("MainFormSelectIconText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Now Playing: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypeNowPlaying() As String
            Get
                Return ResourceManager.GetString("MainFormSkypeNowPlaying", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Now Playing: {0} (Steam).
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypeNowPlayingSteam() As String
            Get
                Return ResourceManager.GetString("MainFormSkypeNowPlayingSteam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stopped Playing: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypePlayStopped() As String
            Get
                Return ResourceManager.GetString("MainFormSkypePlayStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  (Played: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypePlayTimeStopped() As String
            Get
                Return ResourceManager.GetString("MainFormSkypePlayTimeStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to hours.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeHourPlural() As String
            Get
                Return ResourceManager.GetString("MainFormTimeHourPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to hour.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeHourSingular() As String
            Get
                Return ResourceManager.GetString("MainFormTimeHourSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minutes.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeMinutePlural() As String
            Get
                Return ResourceManager.GetString("MainFormTimeMinutePlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minute.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeMinuteSingular() As String
            Get
                Return ResourceManager.GetString("MainFormTimeMinuteSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to seconds.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeSecondPlural() As String
            Get
                Return ResourceManager.GetString("MainFormTimeSecondPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to second.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeSecondSingular() As String
            Get
                Return ResourceManager.GetString("MainFormTimeSecondSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear data....
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormClearDataLinkText() As String
            Get
                Return ResourceManager.GetString("PieChartFormClearDataLinkText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Close.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormCloseButtonText() As String
            Get
                Return ResourceManager.GetString("PieChartFormCloseButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Generate linkable chart.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormGenerateChartButton() As String
            Get
                Return ResourceManager.GetString("PieChartFormGenerateChartButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Labels inside.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormLabelPickerInside() As String
            Get
                Return ResourceManager.GetString("PieChartFormLabelPickerInside", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No labels.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormLabelPickerNone() As String
            Get
                Return ResourceManager.GetString("PieChartFormLabelPickerNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Labels outside.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormLabelPickerOutside() As String
            Get
                Return ResourceManager.GetString("PieChartFormLabelPickerOutside", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oops! There doesn&apos;t seem to be any data recorded. Play some games, then come back!.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormNoData() As String
            Get
                Return ResourceManager.GetString("PieChartFormNoData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please wait.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormPleaseWait() As String
            Get
                Return ResourceManager.GetString("PieChartFormPleaseWait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Save as image....
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSaveAsImageButton() As String
            Get
                Return ResourceManager.GetString("PieChartFormSaveAsImageButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your chart image was saved!.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSaveAsImageSuccess() As String
            Get
                Return ResourceManager.GetString("PieChartFormSaveAsImageSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save pie chart as image.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSaveAsImageTitleBar() As String
            Get
                Return ResourceManager.GetString("PieChartFormSaveAsImageTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show legend.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormShowLegendCheckBox() As String
            Get
                Return ResourceManager.GetString("PieChartFormShowLegendCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to d.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeDayShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeDayShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to h.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeHourShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeHourShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to m.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeMinuteShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeMinuteShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to s.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeSecondShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeSecondShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher Playtime Statistics.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTitleBar() As String
            Get
                Return ResourceManager.GetString("PieChartFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total playing time.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTotalPlayingTime() As String
            Get
                Return ResourceManager.GetString("PieChartFormTotalPlayingTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cancel.
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormCancelButton() As String
            Get
                Return ResourceManager.GetString("RemoveFormCancelButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to remove the selected item(s)?.
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormConfirmRemoval() As String
            Get
                Return ResourceManager.GetString("RemoveFormConfirmRemoval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select the items you wish to remove. You can hold CTRL to select several items at once..
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormFlavorTextLabel() As String
            Get
                Return ResourceManager.GetString("RemoveFormFlavorTextLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No items selected..
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormNoItemsSelected() As String
            Get
                Return ResourceManager.GetString("RemoveFormNoItemsSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Remove item(s).
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormRemoveItemsButton() As String
            Get
                Return ResourceManager.GetString("RemoveFormRemoveItemsButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove item(s).
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormTitleBar() As String
            Get
                Return ResourceManager.GetString("RemoveFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Norsk oversettelse av xdpirate.
        '''</summary>
        Friend Shared ReadOnly Property TranslationAuthor() As String
            Get
                Return ResourceManager.GetString("TranslationAuthor", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
