'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class mlsSerbianCyrillic
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GameLauncher.mlsSerbianCyrillic", GetType(mlsSerbianCyrillic).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher
        '''© 2012-2013 xdpirate
        '''Бета тестирање урадио Kurithas.
        '''Посебна захвалност Лиси за подршку..
        '''</summary>
        Friend Shared ReadOnly Property AboutFormAuthorNote() As String
            Get
                Return ResourceManager.GetString("AboutFormAuthorNote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Затвори.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormCloseButtonText() As String
            Get
                Return ResourceManager.GetString("AboutFormCloseButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Контакт.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormContactText() As String
            Get
                Return ResourceManager.GetString("AboutFormContactText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Доступна је нова верзија Game Launcher-а  (v.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormNewVersion1() As String
            Get
                Return ResourceManager.GetString("AboutFormNewVersion1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Да ли би сте желели да је сада преузмете?.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormNewVersion2() As String
            Get
                Return ResourceManager.GetString("AboutFormNewVersion2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Провери &amp;ажурираност.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpdateCheckButtonText() As String
            Get
                Return ResourceManager.GetString("AboutFormUpdateCheckButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Догодила се грешка током провере ажурираности:.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpdateError1() As String
            Get
                Return ResourceManager.GetString("AboutFormUpdateError1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Молимо Вас покушајте касније или контактирајте аутора ако грешка настави да се јавља..
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpdateError2() As String
            Get
                Return ResourceManager.GetString("AboutFormUpdateError2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ваша инсталација Game Launcher-а је ажурирана!.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpToDate() As String
            Get
                Return ResourceManager.GetString("AboutFormUpToDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Веб сајт.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormWebsiteLinkText() As String
            Get
                Return ResourceManager.GetString("AboutFormWebsiteLinkText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Претражи....
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormBrowseButtons() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormBrowseButtons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Кликните ово дугме да би сте селектовали извршни фајл који служи да би се игра покренула. Ово је типично .exe фајл..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormBrowseExeHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormBrowseExeHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Одустани.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCancelButton() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCancelButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Кликните ово дугме ако желите да одустанете од додавања ове игре. Ако имате више игара спремних да их додате (на пример: ако користите падајући прозор или десним-кликом селектујете у Еxplorer-у), мораћете да кликнете одустајем код сваке..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCancelHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCancelHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Унети аргументе командне линије који ће бити кориштени при покретању игре. Ако не знате шта је ово, поље можете оставити празним..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCmdArgsHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCmdArgsHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Аргументи командне линије:.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCmdArgsLabel() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCmdArgsLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Кликните ово дугме да би сте селектовали своју иконицу. Мора бити BMP, PNG, GIF, JPG или ICO слика и биће промењена на димензије 16x16. Можете и специфицирати и .exe фајл да би сте екстрактовали његову главну икону и користили је. Слика ће задржати своје пропорције..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCustomIconHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCustomIconHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Лебдите мишем преко објеката да би сте приказали помоћ у овом панелу..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormDefaultHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormDefaultHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Морате специфицирати икону ако је  &quot;Узети из неког другог фајла&quot;  селектовано..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorGetFromOtherFileNoIcon() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorGetFromOtherFileNoIcon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Извршни фајл launcher-а није пронађен: .
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorLauncherExeNotFound() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorLauncherExeNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Главни извршни фајл игре није пронађен:.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorMainExeNotFound() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorMainExeNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Морате унети идентификациони код Steam апликације за игру (Steam App ID)..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoAppId() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoAppId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Морате специфицирати путању фајла launcher-у..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoLauncherPath() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoLauncherPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Морате специфицирати путању фајла за главни извршни фајл..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoMainPath() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoMainPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Морате специфицирати име за игру..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoName() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Морате специфицирати путању до извршног фајла који Steam користи да би стартовао игру. .
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoSteamExePath() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoSteamExePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Не можете селектовати “Узети из извршног фајла” за иконицу ако нисте специфицирали извршни фајл за Steam игру..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoSteamExePathClickedGetFromExecutable() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoSteamExePathClickedGetFromExecutable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Морате специфицирати иконицу за ову Steam игру..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoSteamIcon() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoSteamIcon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Специфицирани извршни фајл за Steam игру није пронађен:.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorSteamExeNotFound() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorSteamExeNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Информације о игри.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGameInfoGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGameInfoGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Овде унети име игре. Име може бити било шта, једино што ће знаци једнако (=) бити замењени цртицама (-) због техничких ограничења. .
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGameNameHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGameNameHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Име:.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGameNameLabel() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGameNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Путанја игре/ID Steam апликације.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGamePathsGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGamePathsGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Селектовати ову опцију ако желите да Game Launcher узме иконицу из изабраног извршног фајла игре..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromExeHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromExeHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Узети из извршног фајла..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromExeRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromExeRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Селектовати ову опцију ако желите да сами изаберету иконицу..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromOtherFileHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromOtherFileHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Узети из неког другог фајла..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromOtherFileRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromOtherFileRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Помоћ.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormHelpGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormHelpGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Иконица.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormIconGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormIconGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ово показује преглед иконице која ће бити коришћена. Ако је Game Launcher подешен да преузме иконицу из извршног фајла игре, морате специфицирати извршни фајл пре него што се овај преглед прикаже. .
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormIconHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormIconHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Задржати тренутну иконицу..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormKeepIconRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormKeepIconRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Кликнути ово дугме да би сте селектовали launcher који ће покренути главни извршни фајл игре..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormLauncherBrowseHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormLauncherBrowseHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Селектовати ову опцију ако је ово обична игра (на пример не користи Steam)..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormNormalGameHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormNormalGameHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Обична игра.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormNormalGameRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormNormalGameRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Потврди.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormOKButton() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormOKButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Кликнути ово дугме када сте завршили попуњавање детаља игре коју додајете..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormOKHelp() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormOKHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Специфицирати извршни фајл..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSpecifySteamExeCheckBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSpecifySteamExeCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Откачити овде ако желите да селектујете извршни фајл који Steam користи да би стартовао игру. Ово ће омогућити праћење времена играња за Steam игре. Ако игра користи launcher, нема потребе селектовати ово, једноставно селектујте главни извршни фајл са којим се игра стартује..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSpecifySteamExeHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSpecifySteamExeHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Унесите Steam апликациони идентификациони број овде (Steam App ID). Да би сте пронашли ID, лоцирајте игру у Steam продавници и копирајте ID из последњег дела URL-а (на пример, http://store.steampowered.com/app/24980/ -&gt;  ID је овде 24980).
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamAppIdHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamAppIdHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Кликните овде да пронађете главни извршни фајл који Steam користи да би покренуо игру..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamExeBrowseHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamExeBrowseHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Steam игре.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamGameRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamGameRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Селектујте ову опцију ако је ово игра која мора бити стартована преко Steam-а..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Додати или унети промене за игре..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormTitleBar() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Користи launcher.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormUsesLauncherCheckBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormUsesLauncherCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Откачити овде ако игра коју додајете користи launcher. Launcher је извршни фајл који ће сам покренути главну игру. Ова опција ће омогућити праћење времена играња за игре које захетвају да се покрену launcher-ом..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormUsesLauncherHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormUsesLauncherHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Always on top.
        '''</summary>
        Friend Shared ReadOnly Property DockFormMenuAlwaysOnTop() As String
            Get
                Return ResourceManager.GetString("DockFormMenuAlwaysOnTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change opacity.
        '''</summary>
        Friend Shared ReadOnly Property DockFormMenuChangeOpacity() As String
            Get
                Return ResourceManager.GetString("DockFormMenuChangeOpacity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close the dock.
        '''</summary>
        Friend Shared ReadOnly Property DockFormMenuClose() As String
            Get
                Return ResourceManager.GetString("DockFormMenuClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Провидност дока када је у фокусу (када миш лебди изнад дока) .
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormHoverOpacityGroupBox() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormHoverOpacityGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Провидност дока када није у фокусу.
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormNormalOpacityGroupBox() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormNormalOpacityGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Сними.
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormSaveButton() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormSaveButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Променити провидност.
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormTitleBar() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Убацити шорткат (скраћеницу) или извршни фајл овде!.
        '''</summary>
        Friend Shared ReadOnly Property DragDropTargetFormTitleBar() As String
            Get
                Return ResourceManager.GetString("DragDropTargetFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Линк копиран у клипборд!.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormCopiedToClipBoardText() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormCopiedToClipBoardText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Копирај.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormCopyButton() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormCopyButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Кратки линкови љубазношћу is.gd.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormCourtesyLabel() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormCourtesyLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Успех! Пошаљите доњи линк својим пријатељима и вољенима:.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormFlavorTextLabel() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormFlavorTextLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Затвори.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormGTFOButton() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormGTFOButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Листа података са линком.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormTitleBar() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Посетити линк.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormVisitLinkButton() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormVisitLinkButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Аутоматски проверавај ажурираност.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormAutoUpdateCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormAutoUpdateCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Додати у &amp;Game Launcher.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormExplorerIntegrationText() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormExplorerIntegrationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Затвори.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormGTFOButton() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormGTFOButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Промене имају одмах ефекат. .
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormInfoLabel() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormInfoLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Интегрисати у Windows Explorer.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormIntegrateWithExplorerCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormIntegrateWithExplorerCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Показати време проведено у игрању када се изађе из игре.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormPlayTimeInSkypeNotificationsCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormPlayTimeInSkypeNotificationsCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Подешавања .
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormPreferencesGroupBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormPreferencesGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Послати обавештења Skajp-у када почнете/престанете да се играте.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormSkypeNotificationsCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormSkypeNotificationsCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Стартовати Game Launcher када се улогујете.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormStartOnLoginCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormStartOnLoginCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Подешавања Game Launcher-а.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormTitleBar() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Нешто је пошло по злу! .NET Framework је рекао:.
        '''</summary>
        Friend Shared ReadOnly Property MainFormAddGameFailed1() As String
            Get
                Return ResourceManager.GetString("MainFormAddGameFailed1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ако сматрате да је ово bug, или се порука о грешци изнова понавља, молимо Вас контактирајте аутора..
        '''</summary>
        Friend Shared ReadOnly Property MainFormAddGameFailed2() As String
            Get
                Return ResourceManager.GetString("MainFormAddGameFailed2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Кликните десним дугметом миша ову иконицу или притисните Windows+Г дугмад да би сте отворили листу. .
        '''</summary>
        Friend Shared ReadOnly Property MainFormBalloonTipLoadedMessageText() As String
            Get
                Return ResourceManager.GetString("MainFormBalloonTipLoadedMessageText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher v{0} учитан!.
        '''</summary>
        Friend Shared ReadOnly Property MainFormBalloonTipLoadedMessageTitle() As String
            Get
                Return ResourceManager.GetString("MainFormBalloonTipLoadedMessageTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Да ли сте сигурни да желите да уклоните све елементе у листи? Ова акција се НЕ МОЖЕ накнадно оповргнути!.
        '''</summary>
        Friend Shared ReadOnly Property MainFormClearGameList() As String
            Get
                Return ResourceManager.GetString("MainFormClearGameList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Изменити &amp;игру....
        '''</summary>
        Friend Shared ReadOnly Property MainFormEditGameItem() As String
            Get
                Return ResourceManager.GetString("MainFormEditGameItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Изменити подешавања ове игре.
        '''</summary>
        Friend Shared ReadOnly Property MainFormEditGameItemTooltip() As String
            Get
                Return ResourceManager.GetString("MainFormEditGameItemTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher се учитава, молимо сачекајте....
        '''</summary>
        Friend Shared ReadOnly Property MainFormLoadingMessage() As String
            Get
                Return ResourceManager.GetString("MainFormLoadingMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Постоји нова верзија Game Launcher-а (v{0})! Да ли би сте желели да је сада преузмете?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormNewVersionAvailable1() As String
            Get
                Return ResourceManager.GetString("MainFormNewVersionAvailable1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ако одлучите да не ажурирате сада, провера ажурираности ће бити онемогућена за ову сесију..
        '''</summary>
        Friend Shared ReadOnly Property MainFormNewVersionAvailable2() As String
            Get
                Return ResourceManager.GetString("MainFormNewVersionAvailable2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Опције.
        '''</summary>
        Friend Shared ReadOnly Property MainFormOptionsItem() As String
            Get
                Return ResourceManager.GetString("MainFormOptionsItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Да ли сте сигурни да желите да изађете из Game Launcher-а?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormQuitApplication() As String
            Get
                Return ResourceManager.GetString("MainFormQuitApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Излаз.
        '''</summary>
        Friend Shared ReadOnly Property MainFormQuitItem() As String
            Get
                Return ResourceManager.GetString("MainFormQuitItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Да ли сте сигурни да желите да уклоните све аргументе командне линије за {0}?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveCmdArgs() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveCmdArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Уклонити....
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveGameItem() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveGameItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Уклонити ову игру са листе.
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveGameItemTooltip() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveGameItemTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Да ли сте сигурни да желите да уклоните {0} са листе?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveGameMsg() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveGameMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Селектовати иконицу за &quot;{0}&quot;.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSelectIconText() As String
            Get
                Return ResourceManager.GetString("MainFormSelectIconText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Тренутно се игра: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypeNowPlaying() As String
            Get
                Return ResourceManager.GetString("MainFormSkypeNowPlaying", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Тренутно се игра: {0} (Steam).
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypeNowPlayingSteam() As String
            Get
                Return ResourceManager.GetString("MainFormSkypeNowPlayingSteam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Престао са игром: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypePlayStopped() As String
            Get
                Return ResourceManager.GetString("MainFormSkypePlayStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  (Играо: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypePlayTimeStopped() As String
            Get
                Return ResourceManager.GetString("MainFormSkypePlayTimeStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to сати.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeHourPlural() As String
            Get
                Return ResourceManager.GetString("MainFormTimeHourPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to сат .
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeHourSingular() As String
            Get
                Return ResourceManager.GetString("MainFormTimeHourSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to минути.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeMinutePlural() As String
            Get
                Return ResourceManager.GetString("MainFormTimeMinutePlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to минут.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeMinuteSingular() As String
            Get
                Return ResourceManager.GetString("MainFormTimeMinuteSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to секунди.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeSecondPlural() As String
            Get
                Return ResourceManager.GetString("MainFormTimeSecondPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to секунд.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeSecondSingular() As String
            Get
                Return ResourceManager.GetString("MainFormTimeSecondSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Показује информације о апликацији и људима који су допринели раду апликације..
        '''</summary>
        Friend Shared ReadOnly Property MainMenuAboutTooltip() As String
            Get
                Return ResourceManager.GetString("MainMenuAboutTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Додати игру на листу. Можете исто тако двоструким кликом на иконицу у System Tray-у (најчешће доле десни угао у Windows-у) брзо додавати игрице превлачећи и испуштајући шорткатове (скраћенице) или извршне фајлове..
        '''</summary>
        Friend Shared ReadOnly Property MainMenuAddGameTooltip() As String
            Get
                Return ResourceManager.GetString("MainMenuAddGameTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Обрисати сваки елемент у листи игара. Ова акција се не може накнадно оповргнути!.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuClearGameListTooltip() As String
            Get
                Return ResourceManager.GetString("MainMenuClearGameListTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Опције.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptions() As String
            Get
                Return ResourceManager.GetString("MainMenuOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to О &amp;Game Launcher-у.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsAbout() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsAbout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Додај игре....
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsAddGame() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsAddGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Очисти листу игара....
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsClearGameList() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsClearGameList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Подешавања.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsPreferences() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsPreferences", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Уклони игре....
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsRemoveGames() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsRemoveGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Статистике.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsStatistics() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsStatistics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Излаз.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuQuit() As String
            Get
                Return ResourceManager.GetString("MainMenuQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Уклонити једну или више игара са листе..
        '''</summary>
        Friend Shared ReadOnly Property MainMenuRemoveGamesTooltip() As String
            Get
                Return ResourceManager.GetString("MainMenuRemoveGamesTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Очистити граф....
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormClearDataLinkText() As String
            Get
                Return ResourceManager.GetString("PieChartFormClearDataLinkText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Одустани.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormCloseButtonText() As String
            Get
                Return ResourceManager.GetString("PieChartFormCloseButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Генериши податке са линком.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormGenerateChartButton() As String
            Get
                Return ResourceManager.GetString("PieChartFormGenerateChartButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ознаке унутра.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormLabelPickerInside() As String
            Get
                Return ResourceManager.GetString("PieChartFormLabelPickerInside", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Без ознака.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormLabelPickerNone() As String
            Get
                Return ResourceManager.GetString("PieChartFormLabelPickerNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ознаке споља.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormLabelPickerOutside() As String
            Get
                Return ResourceManager.GetString("PieChartFormLabelPickerOutside", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ууупс! Изгледа да нема никаквих снимљених података. Играјте неке игре, па се онда вратите!.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormNoData() As String
            Get
                Return ResourceManager.GetString("PieChartFormNoData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Молимо сачекајте.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormPleaseWait() As String
            Get
                Return ResourceManager.GetString("PieChartFormPleaseWait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Сними као слику....
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSaveAsImageButton() As String
            Get
                Return ResourceManager.GetString("PieChartFormSaveAsImageButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ваша слика података је снимљена!.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSaveAsImageSuccess() As String
            Get
                Return ResourceManager.GetString("PieChartFormSaveAsImageSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Снимити граф као слику.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSaveAsImageTitleBar() As String
            Get
                Return ResourceManager.GetString("PieChartFormSaveAsImageTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Приказати легенду.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormShowLegendCheckBox() As String
            Get
                Return ResourceManager.GetString("PieChartFormShowLegendCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Сортирај по абецедном реду.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSortingPickerAlphabetically() As String
            Get
                Return ResourceManager.GetString("PieChartFormSortingPickerAlphabetically", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Сортирај по броју мечева.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSortingPickerByMostPlayed() As String
            Get
                Return ResourceManager.GetString("PieChartFormSortingPickerByMostPlayed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to д.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeDayShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeDayShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ч.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeHourShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeHourShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to м .
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeMinuteShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeMinuteShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to с .
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeSecondShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeSecondShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher статистике играња.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTitleBar() As String
            Get
                Return ResourceManager.GetString("PieChartFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Укупно време играња.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTotalPlayingTime() As String
            Get
                Return ResourceManager.GetString("PieChartFormTotalPlayingTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Одустани.
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormCancelButton() As String
            Get
                Return ResourceManager.GetString("RemoveFormCancelButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Да ли сте сигурни да желите да уклоните селектован(е) елемент(е)?.
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormConfirmRemoval() As String
            Get
                Return ResourceManager.GetString("RemoveFormConfirmRemoval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Молимо Вас да селектујете елементе које би сте желели да уклоните. Можете држати CTRL да би сте селектовали неколико елемената одједном..
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormFlavorTextLabel() As String
            Get
                Return ResourceManager.GetString("RemoveFormFlavorTextLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ниједан елемент није селектован..
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormNoItemsSelected() As String
            Get
                Return ResourceManager.GetString("RemoveFormNoItemsSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Уклони елемент(е).
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormRemoveItemsButton() As String
            Get
                Return ResourceManager.GetString("RemoveFormRemoveItemsButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Уклонити елемент(е).
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormTitleBar() As String
            Get
                Return ResourceManager.GetString("RemoveFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Превео на српски ћирилицом Rosenkranz.
        '''</summary>
        Friend Shared ReadOnly Property TranslationAuthor() As String
            Get
                Return ResourceManager.GetString("TranslationAuthor", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
