'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class mlsSpanish
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GameLauncher.mlsSpanish", GetType(mlsSpanish).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher
        '''© 2012-2013 xdpirate
        '''Prueba Beta por Kurithas.
        '''Agradecimientos especiales a Lisa por su apoyo..
        '''</summary>
        Friend Shared ReadOnly Property AboutFormAuthorNote() As String
            Get
                Return ResourceManager.GetString("AboutFormAuthorNote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cerrar.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormCloseButtonText() As String
            Get
                Return ResourceManager.GetString("AboutFormCloseButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contacto.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormContactText() As String
            Get
                Return ResourceManager.GetString("AboutFormContactText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hay una nueva versión de Game Launcher disponible (v.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormNewVersion1() As String
            Get
                Return ResourceManager.GetString("AboutFormNewVersion1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Le gustaría descargarla ahora?.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormNewVersion2() As String
            Get
                Return ResourceManager.GetString("AboutFormNewVersion2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buscar &amp;actualizaciones.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpdateCheckButtonText() As String
            Get
                Return ResourceManager.GetString("AboutFormUpdateCheckButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ocurrió un error mientras se buscaba actualizaciones:.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpdateError1() As String
            Get
                Return ResourceManager.GetString("AboutFormUpdateError1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor inténtelo nuevamente más tarde o contacte al autor si los problemas persisten..
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpdateError2() As String
            Get
                Return ResourceManager.GetString("AboutFormUpdateError2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Su instalación de Game Launcher al día..
        '''</summary>
        Friend Shared ReadOnly Property AboutFormUpToDate() As String
            Get
                Return ResourceManager.GetString("AboutFormUpToDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sitio web.
        '''</summary>
        Friend Shared ReadOnly Property AboutFormWebsiteLinkText() As String
            Get
                Return ResourceManager.GetString("AboutFormWebsiteLinkText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Explorar....
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormBrowseButtons() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormBrowseButtons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dele click a este botón para seleccionar el ejecutable utilizado para correr el juego. Éste es, típicamente, un archivo tipo .exe..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormBrowseExeHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormBrowseExeHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cancelar.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCancelButton() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCancelButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Haga clic en este botón si desea cancelar la adición de este juego. Si tiene más juegos en cola para ser añadidos (por ejemplo, si utiliza la ventana desplegable o por click derecho en el Explorador), tendrá que cancelarlos a todos..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCancelHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCancelHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Introduzca las líneas de comandos que desea utilizar para iniciar el juego. Si usted no sabe lo que es esto, puede dejarlo en blanco..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCmdArgsHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCmdArgsHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Línea de comando:.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCmdArgsLabel() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCmdArgsLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Haga clic en este botón para seleccionar un icono personalizado. Debe ser una imagen tipo ICO, BMP, PNG, GIF o JPG, y será redimensionada a 16x16. También puede especificar un archivo EXE para extraer su icono principal y utilizarlo. La imagen conservará sus proporciones..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormCustomIconHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormCustomIconHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pose el ratón sobre un elemento para mostrar un mensaje de ayuda en este panel.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormDefaultHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormDefaultHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe especificar un icono si &quot;Traer desde otro archivo&quot; está seleccionado..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorGetFromOtherFileNoIcon() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorGetFromOtherFileNoIcon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El ejecutable del lanzador no ha sido encontrado:.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorLauncherExeNotFound() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorLauncherExeNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El ejecutable principal del juego no ha sido encontrado:.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorMainExeNotFound() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorMainExeNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe insertar la ID de Steam para el juego..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoAppId() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoAppId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe especificar la ruta de acceso al lanzador.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoLauncherPath() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoLauncherPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe especificar la ruta de acceso al ejecutable..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoMainPath() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoMainPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe especificar un nombre para el juego..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoName() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe especificar la ruta de acceso al ejecutable que Steam utiliza para iniciar el juego..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoSteamExePath() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoSteamExePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No puede seleccionar &quot;Traer desde otro archivo&quot; para el icono si no a especificado el ejecutable para un juego de Steam..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoSteamExePathClickedGetFromExecutable() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoSteamExePathClickedGetFromExecutable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Debe especificar un icono para este juego de Steam..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorNoSteamIcon() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorNoSteamIcon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El ejecutable para el juego de Steam especificado no ha sido encontrado: .
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormErrorSteamExeNotFound() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormErrorSteamExeNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Información del juego..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGameInfoGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGameInfoGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Introduzca el nombre del juego aquí. Puede tener cualquier nombre, pero signos de igual (=) será reemplazado con guiones (-) debido a limitaciones técnicas..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGameNameHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGameNameHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre:.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGameNameLabel() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGameNameLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ruta de acceso/ID deSteam.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGamePathsGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGamePathsGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selecciones esta opción si desea que Game Launcher extraiga el icono del juego desde el ejecutable seleccionado..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromExeHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromExeHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Traer desde el ejecutable.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromExeRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromExeRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccione esta opción si desea especificar un icono usted mismo..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromOtherFileHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromOtherFileHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Traer desde otro archivo.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormGetFromOtherFileRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormGetFromOtherFileRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ayuda.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormHelpGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormHelpGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Icono.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormIconGroupBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormIconGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esto muestra una vista previa del icono que se utilizará. Si Game Launcher está configurado para traer el icono desde el ejecutable del juego, antes debe especificar el ejecutable para que esta vista se actualice..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormIconHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormIconHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conservar el icono actuel.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormKeepIconRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormKeepIconRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Haga clic en este botón para seleccionar el lanzador del ejecutable principal del juego.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormLauncherBrowseHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormLauncherBrowseHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccione esta opción si es un juego normal (e.g. no utiliza Steam).
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormNormalGameHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormNormalGameHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Juego normal.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormNormalGameRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormNormalGameRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;OK.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormOKButton() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormOKButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Haga clic en este botón cuando haya finalizado los detalles del juego que se añade..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormOKHelp() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormOKHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Especificar ejecutable.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSpecifySteamExeCheckBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSpecifySteamExeCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Marque esta casilla si desea seleccionar el ejecutable que Steam utiliza para ejecutar el juego. Habilitar esto permitirá el seguimiento de tiempo de los juegos para Steam. Si el juego ya usa un lanzador, no es necesario seleccionarlo, sólo tiene que seleccionar el ejecutable principal del juego..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSpecifySteamExeHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSpecifySteamExeHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Introduzca el Steam ID aquí. Para encontrar el ID, busque el juego en la tienda de Steam y copie el número de la última parte de la URL (e.g. http://store.steampowered.com/app/24980/ -&gt; El ID es 24980).
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamAppIdHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamAppIdHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Haga clic aquí para buscar el ejecutable principal que Steam utiliza para correr el juego..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamExeBrowseHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamExeBrowseHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Juego de Steam.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamGameRadio() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamGameRadio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccione esta opción si es un juego que debe ser lanzado a través de Steam..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormSteamHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormSteamHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adicionar o editar un juego.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormTitleBar() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usa un lanzador.
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormUsesLauncherCheckBox() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormUsesLauncherCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Marque esta casilla si el juego que está agregando utiliza un lanzador. Un lanzador es un ejecutable independiente que, a su vez, inicia el juego principal. Habilitar que esto permitirá el seguimiento de tiempo de juego para los juegos que requieren ser ejecutados a través de un lanzador..
        '''</summary>
        Friend Shared ReadOnly Property AddNewGameFormUsesLauncherHelpText() As String
            Get
                Return ResourceManager.GetString("AddNewGameFormUsesLauncherHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opacidad cuando está activo.
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormHoverOpacityGroupBox() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormHoverOpacityGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opacidad cuando no está activo.
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormNormalOpacityGroupBox() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormNormalOpacityGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;rGuardar.
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormSaveButton() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormSaveButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cambiar opacidad.
        '''</summary>
        Friend Shared ReadOnly Property DockOpacityFormTitleBar() As String
            Get
                Return ResourceManager.GetString("DockOpacityFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Traiga un acceso directo o un ejecutable aquí!.
        '''</summary>
        Friend Shared ReadOnly Property DragDropTargetFormTitleBar() As String
            Get
                Return ResourceManager.GetString("DragDropTargetFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enlace copiado al portapapeles!.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormCopiedToClipBoardText() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormCopiedToClipBoardText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Copiar.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormCopyButton() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormCopyButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shortlinks por cortesía de is.gd.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormCourtesyLabel() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormCourtesyLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Éxito! Envía el siguiente enlace a tus amigos y seres queridos:.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormFlavorTextLabel() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormFlavorTextLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cerrar&amp;.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormGTFOButton() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormGTFOButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tabla vinculable.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormTitleBar() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Visitar enlace.
        '''</summary>
        Friend Shared ReadOnly Property EmbeddableChartFormVisitLinkButton() As String
            Get
                Return ResourceManager.GetString("EmbeddableChartFormVisitLinkButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buscar actualizaciones automáticamente..
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormAutoUpdateCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormAutoUpdateCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adicionar a &amp;Game Launcher.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormExplorerIntegrationText() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormExplorerIntegrationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cerrar.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormGTFOButton() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormGTFOButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Los cambios entrarán en efecto inmediatamente..
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormInfoLabel() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormInfoLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Integrar con el Explorador de Windows..
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormIntegrateWithExplorerCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormIntegrateWithExplorerCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mostrar el tiempo de juego al salir del juego.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormPlayTimeInSkypeNotificationsCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormPlayTimeInSkypeNotificationsCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preferencias.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormPreferencesGroupBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormPreferencesGroupBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enviar notificaciones a Skype cuando comience o termine de jugar..
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormSkypeNotificationsCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormSkypeNotificationsCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Iniciar Game Launcher cuando inicie sesión.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormStartOnLoginCheckBox() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormStartOnLoginCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preferencias de Game Launcher.
        '''</summary>
        Friend Shared ReadOnly Property GLOptionsFormTitleBar() As String
            Get
                Return ResourceManager.GetString("GLOptionsFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Algo salió mal! .NET Framework dice:.
        '''</summary>
        Friend Shared ReadOnly Property MainFormAddGameFailed1() As String
            Get
                Return ResourceManager.GetString("MainFormAddGameFailed1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Si cree que es un error de programación, o si el mensaje persiste, por favor contacte al autor..
        '''</summary>
        Friend Shared ReadOnly Property MainFormAddGameFailed2() As String
            Get
                Return ResourceManager.GetString("MainFormAddGameFailed2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Haga click derecho en este icono o presione Windows+G Para abrir la lista..
        '''</summary>
        Friend Shared ReadOnly Property MainFormBalloonTipLoadedMessageText() As String
            Get
                Return ResourceManager.GetString("MainFormBalloonTipLoadedMessageText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher v{0} Cargado!.
        '''</summary>
        Friend Shared ReadOnly Property MainFormBalloonTipLoadedMessageTitle() As String
            Get
                Return ResourceManager.GetString("MainFormBalloonTipLoadedMessageTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Está seguro que desea eliminar todos los elementos de la lista? ¡Esta acción  NO se puede deshacer!.
        '''</summary>
        Friend Shared ReadOnly Property MainFormClearGameList() As String
            Get
                Return ResourceManager.GetString("MainFormClearGameList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editar &amp;juego....
        '''</summary>
        Friend Shared ReadOnly Property MainFormEditGameItem() As String
            Get
                Return ResourceManager.GetString("MainFormEditGameItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit propiedades de este juego.
        '''</summary>
        Friend Shared ReadOnly Property MainFormEditGameItemTooltip() As String
            Get
                Return ResourceManager.GetString("MainFormEditGameItemTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Launcher está cargando, por favor espere....
        '''</summary>
        Friend Shared ReadOnly Property MainFormLoadingMessage() As String
            Get
                Return ResourceManager.GetString("MainFormLoadingMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hay una nueva versión de Game Launcher disponible (v{0})! Desea descargarla ahora?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormNewVersionAvailable1() As String
            Get
                Return ResourceManager.GetString("MainFormNewVersionAvailable1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Si decide no actualizar ahora, la búsqueda de actualizaciones se desactivará por esta sesión..
        '''</summary>
        Friend Shared ReadOnly Property MainFormNewVersionAvailable2() As String
            Get
                Return ResourceManager.GetString("MainFormNewVersionAvailable2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Opciones.
        '''</summary>
        Friend Shared ReadOnly Property MainFormOptionsItem() As String
            Get
                Return ResourceManager.GetString("MainFormOptionsItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Está seguro que desea salir de Game Launcher?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormQuitApplication() As String
            Get
                Return ResourceManager.GetString("MainFormQuitApplication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Salir.
        '''</summary>
        Friend Shared ReadOnly Property MainFormQuitItem() As String
            Get
                Return ResourceManager.GetString("MainFormQuitItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Está seguro de que desea eliminar todas las línea de comandos para {0}?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveCmdArgs() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveCmdArgs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El&amp;iminar....
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveGameItem() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveGameItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar este juego de la lista..
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveGameItemTooltip() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveGameItemTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Está seguro de que desea eliminar a {0} de la lista?.
        '''</summary>
        Friend Shared ReadOnly Property MainFormRemoveGameMsg() As String
            Get
                Return ResourceManager.GetString("MainFormRemoveGameMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccione icono para &quot;{0}&quot;.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSelectIconText() As String
            Get
                Return ResourceManager.GetString("MainFormSelectIconText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jugando: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypeNowPlaying() As String
            Get
                Return ResourceManager.GetString("MainFormSkypeNowPlaying", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jugando: {0} (Steam).
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypeNowPlayingSteam() As String
            Get
                Return ResourceManager.GetString("MainFormSkypeNowPlayingSteam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dejó de jugar: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypePlayStopped() As String
            Get
                Return ResourceManager.GetString("MainFormSkypePlayStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  (Jugó: {0}.
        '''</summary>
        Friend Shared ReadOnly Property MainFormSkypePlayTimeStopped() As String
            Get
                Return ResourceManager.GetString("MainFormSkypePlayTimeStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to horas.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeHourPlural() As String
            Get
                Return ResourceManager.GetString("MainFormTimeHourPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to horas.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeHourSingular() As String
            Get
                Return ResourceManager.GetString("MainFormTimeHourSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minutos.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeMinutePlural() As String
            Get
                Return ResourceManager.GetString("MainFormTimeMinutePlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to minuto.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeMinuteSingular() As String
            Get
                Return ResourceManager.GetString("MainFormTimeMinuteSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to segundos.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeSecondPlural() As String
            Get
                Return ResourceManager.GetString("MainFormTimeSecondPlural", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to segundo.
        '''</summary>
        Friend Shared ReadOnly Property MainFormTimeSecondSingular() As String
            Get
                Return ResourceManager.GetString("MainFormTimeSecondSingular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Muestra información acerca de la aplicación y sus colaboradores..
        '''</summary>
        Friend Shared ReadOnly Property MainMenuAboutTooltip() As String
            Get
                Return ResourceManager.GetString("MainMenuAboutTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agregar un juego a la lista. También puede hacer doble clic en el icono de la bandeja para añadir juegos rápidamente arrastrando y soltando los accesos directos o los ejecutables..
        '''</summary>
        Friend Shared ReadOnly Property MainMenuAddGameTooltip() As String
            Get
                Return ResourceManager.GetString("MainMenuAddGameTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar todos los elementos de la lista de juegos. ¡Esta acción  no se puede deshacer!.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuClearGameListTooltip() As String
            Get
                Return ResourceManager.GetString("MainMenuClearGameListTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Opciones.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptions() As String
            Get
                Return ResourceManager.GetString("MainMenuOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aceca de &amp;Game Launcher.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsAbout() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsAbout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Añadir juego....
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsAddGame() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsAddGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Limpiar lista de juegos....
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsClearGameList() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsClearGameList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Preferencias.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsPreferences() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsPreferences", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Remover juegos....
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsRemoveGames() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsRemoveGames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Estadísticas.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuOptionsStatistics() As String
            Get
                Return ResourceManager.GetString("MainMenuOptionsStatistics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Salir.
        '''</summary>
        Friend Shared ReadOnly Property MainMenuQuit() As String
            Get
                Return ResourceManager.GetString("MainMenuQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar uno o más juegos de la lista..
        '''</summary>
        Friend Shared ReadOnly Property MainMenuRemoveGamesTooltip() As String
            Get
                Return ResourceManager.GetString("MainMenuRemoveGamesTooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Borrar datos....
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormClearDataLinkText() As String
            Get
                Return ResourceManager.GetString("PieChartFormClearDataLinkText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cerrar.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormCloseButtonText() As String
            Get
                Return ResourceManager.GetString("PieChartFormCloseButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Generar tabla vinculable.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormGenerateChartButton() As String
            Get
                Return ResourceManager.GetString("PieChartFormGenerateChartButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Etiquetas en el interior.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormLabelPickerInside() As String
            Get
                Return ResourceManager.GetString("PieChartFormLabelPickerInside", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sin etiquetas.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormLabelPickerNone() As String
            Get
                Return ResourceManager.GetString("PieChartFormLabelPickerNone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Etiquetas en el exterior.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormLabelPickerOutside() As String
            Get
                Return ResourceManager.GetString("PieChartFormLabelPickerOutside", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Oops! No parece haber ningún dato guardado. Juega algunos juegos y luego regresa..
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormNoData() As String
            Get
                Return ResourceManager.GetString("PieChartFormNoData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor espere.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormPleaseWait() As String
            Get
                Return ResourceManager.GetString("PieChartFormPleaseWait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Guardar como imagen....
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSaveAsImageButton() As String
            Get
                Return ResourceManager.GetString("PieChartFormSaveAsImageButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡La imagen de su tabla ha sido guardada!.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSaveAsImageSuccess() As String
            Get
                Return ResourceManager.GetString("PieChartFormSaveAsImageSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guardar gráfico como imagen.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormSaveAsImageTitleBar() As String
            Get
                Return ResourceManager.GetString("PieChartFormSaveAsImageTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mostrar leyenda.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormShowLegendCheckBox() As String
            Get
                Return ResourceManager.GetString("PieChartFormShowLegendCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to d.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeDayShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeDayShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to h.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeHourShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeHourShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to m.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeMinuteShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeMinuteShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to s.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTimeSecondShorthand() As String
            Get
                Return ResourceManager.GetString("PieChartFormTimeSecondShorthand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estadísticas de tiempo de juego de Game Launcher.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTitleBar() As String
            Get
                Return ResourceManager.GetString("PieChartFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tiempo de juego total.
        '''</summary>
        Friend Shared ReadOnly Property PieChartFormTotalPlayingTime() As String
            Get
                Return ResourceManager.GetString("PieChartFormTotalPlayingTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cancelar.
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormCancelButton() As String
            Get
                Return ResourceManager.GetString("RemoveFormCancelButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Está seguro que desea eliminar los elementos selecionados?.
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormConfirmRemoval() As String
            Get
                Return ResourceManager.GetString("RemoveFormConfirmRemoval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor, seleccione los elementos que desea eliminar. Puede dejar presionado CTRL para seleccionar varios elementos a la vez..
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormFlavorTextLabel() As String
            Get
                Return ResourceManager.GetString("RemoveFormFlavorTextLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ningún elemento seleccionado..
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormNoItemsSelected() As String
            Get
                Return ResourceManager.GetString("RemoveFormNoItemsSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Eliminar elemento(s).
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormRemoveItemsButton() As String
            Get
                Return ResourceManager.GetString("RemoveFormRemoveItemsButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar elemento(s).
        '''</summary>
        Friend Shared ReadOnly Property RemoveFormTitleBar() As String
            Get
                Return ResourceManager.GetString("RemoveFormTitleBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Traducción al español por Dan0..
        '''</summary>
        Friend Shared ReadOnly Property TranslationAuthor() As String
            Get
                Return ResourceManager.GetString("TranslationAuthor", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
